version: '3'
services:
  php-fpm:
    build:
      context: ./docker/php
      dockerfile: php-fpm.docker
    volumes:
      - .:/app
    depends_on:
      - mysql

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: nginx.docker
    volumes:
      - .:/app
    depends_on:
      - php-fpm
    ports:
      - '8080:80'

  php-cli:
    build:
      context: ./docker/php
      dockerfile: php-cli.docker
    volumes:
      - ./:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - '33062:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=api

  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1